# Generated by Django 5.1.1 on 2024-09-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_videoitem_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
