# Generated by Django 5.1.1 on 2024-09-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_videoitem_name_alter_videoitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
