# Generated by Django 5.1.1 on 2024-09-24 08:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_videoitem_name_alter_videoitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='video_file',
            field=models.FileField(default=[], upload_to='videos'),
            preserve_default=False,
        ),
    ]
