# Generated by Django 5.1.1 on 2024-09-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_videoitem_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='has_sound',
            field=models.BooleanField(default=False),
        ),
    ]
